steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/brownbagdemo-378700/brownbag-demo:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/brownbagdemo-378700/brownbag-demo:$COMMIT_SHA',
      ]  
 - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'cloud-run-continuous-deployment-example',
        '--image=gcr.io/brownbagdemo-378700/brownbag-demo:$SHORT_SHA',
        '--region=us-central1',
      ]
